### ISSUE TITLE
unable to update dependencies

### ISSUE THREAD

**Issue by Th0rgal** [software-mansion/protostar#1100]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.6.0`  |
| Cairo-lang | `0.10.0` |
| Git        | `2.37.1`        |

## Current Behavior

When cloning https://github.com/starknet-id/naming_contract, commit ``61b638a69a21624f8fd99bcaf15d1f3dbc5bc108`` and running ``protostar install``, it installs old versions of the dependency starknetid. Running ``protostar update`` doesn't update it.

Here is the gitmodules:
```toml
[submodule "cairo_contracts"]
	path = lib/cairo_contracts
	url = https://github.com/OpenZeppelin/cairo-contracts/
[submodule "starknetid"]
	path = lib/starknetid
	url = https://github.com/starknet-id/contract
```

## Expected Behavior

It should install last version of the dependencies specified.

## Steps to Reproduce

1. clone https://github.com/starknet-id/naming_contract/
3. cd directory
4. git checkout 61b638a69a21624f8fd99bcaf15d1f3dbc5bc108
5. protostar install
6. protostar update
