### ISSUE TITLE
`CAIROPATH` manipulation does not work with profiles

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#1181]
https://discord.com/channels/793094838509764618/964116575387021413/1044168146120085514

## Steps to Reproduce

**Prepare virtual environment**
```shell
asdf local python 3.9.14
python -m venv env
. env/bin/activate
pip install py_vollib
```

**protostar.toml**
```toml
[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["env/lib/python3.9/site-packages"]

[contracts]
main = ["src/main.cairo"]

[profile.foo.test]
target = ["tests/test_main.cairo"]
```

**tests/test_main.cairo**
```cairo
%lang starknet

@external
func test_foo() {
    %{ from py_vollib import black_scholes %}
    return ();
}
```

**run**
```shell
protostar -p foo test
```

```
Traceback (most recent call last):
  File "tests/test_main.cairo", line 5, in <module>
    %{ from py_vollib import black_scholes %}
ModuleNotFoundError: No module named 'py_vollib'
```

**but this works**
```shell
protostar test
```
