### ISSUE TITLE
Disable hint verification in protostar.toml

### ISSUE THREAD

**Issue by milancermak** [software-mansion/protostar#441]
In #382, we got a command line arg to disable hint verification, which is cool. 

I believe this should be the default setting, hint validation should be disabled for all tests all the time, since there's virtually no downsides to it, but it helps with debugging (e.g. with `%{ print() %}` statements).

Instead of selectively passing the `--disable-hint-validation` through the cmdline, can we please have a setting in `protostar.toml` that sets the value of this flag? Something like:

```toml

["protostar.test"]
hint-validation = false
```

**Comment by kasperski95** [comment]
You can already configure any optional argument in the `protostar.toml` like this:

```toml
["protostar.test"]
disable-hint-validation = true
```

I wouldn't change the default value because:
- some people may use invalid hint and they may not notice it until running `protostar build` increasing the feedback loop
- consistency — `disable-hint-validation` works in the same way for 2 commands
- strict by default approach
